#!/usr/bin/env python3
"""
convert_tables.py

Converts Sybase ASE 15 table DDL scripts to Oracle 19c DDL scripts.

Usage:
    python convert_tables.py /full/path/to/sybase/table/ddls
"""

import os
import re
import sys
from pathlib import Path


DATA_TYPE_MAP = {
    r"\bINT\b": "NUMBER(10)",
    r"\bBIGINT\b": "NUMBER(19)",
    r"\bSMALLINT\b": "NUMBER(5)",
    r"\bTINYINT\b": "NUMBER(3)",
    r"\bVARCHAR\b": "VARCHAR2",
    r"\bCHAR\b": "CHAR",
    r"\bDATETIME\b": "TIMESTAMP",
    r"\bDATE\b": "DATE",
    r"\bBIT\b": "NUMBER(1)",
    r"\bTEXT\b": "CLOB",
    r"\bIMAGE\b": "BLOB",
    r"\bNUMERIC\b": "NUMBER",
    r"\bDECIMAL\b": "NUMBER",
}


def convert_identity(sql: str) -> str:
    """
    Convert Sybase IDENTITY to Oracle identity
    """
    sql = re.sub(
        r"\bIDENTITY\b",
        "GENERATED BY DEFAULT AS IDENTITY",
        sql,
        flags=re.IGNORECASE
    )
    return sql


def convert_data_types(sql: str) -> str:
    """
    Convert Sybase datatypes to Oracle datatypes
    """
    for syb_type, ora_type in DATA_TYPE_MAP.items():
        sql = re.sub(syb_type, ora_type, sql, flags=re.IGNORECASE)
    return sql


def cleanup_syntax(sql: str) -> str:
    """
    Remove Sybase-specific syntax
    """
    # Remove GO statements
    sql = re.sub(r"^\s*GO\s*$", "", sql, flags=re.IGNORECASE | re.MULTILINE)

    # Remove WITH clauses on tables/indexes
    sql = re.sub(r"\bWITH\s*\(.*?\)", "", sql, flags=re.IGNORECASE | re.DOTALL)

    # Normalize semicolons
    sql = sql.strip()
    if not sql.endswith(";"):
        sql += ";"

    return sql


def convert_table_ddl(sql: str) -> str:
    """
    Master conversion function for table DDL
    """
    sql = sql.replace("\r\n", "\n")

    sql = convert_identity(sql)
    sql = convert_data_types(sql)
    sql = cleanup_syntax(sql)

    return sql


def process_folder(folder_path: str):
    """
    Process all .sql files in the given folder
    """
    folder = Path(folder_path)

    if not folder.exists() or not folder.is_dir():
        print(f"ERROR: Invalid directory: {folder_path}")
        sys.exit(1)

    sql_files = list(folder.glob("*.sql"))

    if not sql_files:
        print("No .sql files found.")
        return

    for sql_file in sql_files:
        print(f"Converting: {sql_file.name}")

        with open(sql_file, "r", encoding="utf-8") as f:
            sybase_sql = f.read()

        oracle_sql = convert_table_ddl(sybase_sql)

        output_file = sql_file.with_name(sql_file.stem + "_ora.sql")

        with open(output_file, "w", encoding="utf-8") as f:
            f.write("-- Auto-generated Oracle 19c DDL\n")
            f.write("-- Source: Sybase ASE 15\n\n")
            f.write(oracle_sql)
            f.write("\n")

        print(f"Created: {output_file.name}")

    print("✅ Table DDL conversion completed.")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python convert_tables.py <folder_path>")
        sys.exit(1)

    process_folder(sys.argv[1])
